baseurl      = "localhost"
title        = "Alexander Weir"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Student at Liberty University"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Alexander Weir's Website"
  keywords = "homepage, personal"
  images = [""]

    [params.footer]
    trademark = 2025
    rss = false
    copyright = true
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Theme by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

    [[params.social]]
    name = "email"
    url  = "mailto:alexstore06@gmail.com"

    [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/alexander-weir-0b5521261/"

    [[params.social]]
    name = "github"
    url = "https://github.com/alexstore06"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Alexander Weir"

    copyright = '<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>'
    

  [languages.en.params]
#    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "alexander weir"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
#  [[menu.main]]
#    identifier = "resume"
#    name       = "Resume"
#    url        = "/Resume2025.pdf"
#    weight     = 1
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 4
